server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:usersdb}
    username: ${DB_USER:appuser}
    password: ${DB_PASSWORD:apppwd}
  sql:
    init:
      mode: always
management:
  endpoints.web.exposure.include: health, info
